### ISSUE TITLE
Spectral Norm of Hermitian matrix

### ISSUE THREAD

**Issue by BEpresent** [gsagnol/picos#15]
Dear all,

I did not find a function for the spectral norm of a matrix (i.e. the largest singular value).

I want to minimize the spectral norm of a positive semidefinite Hermitian matrix Z.

I would add it like this:

Z = P.add_variable('X',(8,8),'hermitian')

I have found the function abs(), and also looked at http://picos.zib.de/tools.html?highlight=norm#picos.tools.norm, 

however, I did not find the spectral norm. Did I miss something?

I tried to set the objective as

P.set_objective( 'min', abs(Z))   together with some constraints

But this also did not work. 

Any help would be appreciated.

**Comment by gsagnol** [comment]
You can add an auxiliary scalar variable for the minimization:
t = P.add_variable('t',1)
Then,  use the function lambda_max: http://picos.zib.de/tools.html?highlight=norm#picos.tools.lambda_max

P.add_constraint(pic.tools.lambda_max(Z)<t)
P.minimize(t)

Note: If your matrix X is real-valued, then declare it as 'symmetric' rather than 'hermitian', this will avoid some computational burden !
