### ISSUE TITLE
About horizontal concatenation

### ISSUE THREAD

**Issue by colombojrj** [gsagnol/picos#22]
Hello friends,

I am having some trouble with the following concatenation:
prob = pic.Problem()
g = prob.add_variable('g', (1,1))
c = (0 & 0 & g)

Python returns : 
# (1 x 2)-affine expression: [0,g]

However, I tried to make # (1 x 3)-affine expression: [0,0,g] #.

I am reporting because I think it is a bug. If I am wrong, please, do not consider this report.

Thanks and again, congratulation by PICOS.

**Comment by gsagnol** [comment]
Hi,

This is not really a bug:
when you type (0 & 0 & g),

python evaluates first (0 & 0) which makes 0, because for 2 integer,  '&' is the bitwise 'and' operator.

Note that c = (0 & (0 & g)) 
returns what you would expect.

But the most 'picosian' way to do this would be something like:
zero = pic.newparam('0',0)
c = (zero & zero & g)

Best !

**Comment by colombojrj** [comment]
That solved. Thanks, man!

Em 02-05-2016 16:50, gsagnol escreveu:

> Closed #22 https://github.com/gsagnol/picos/issues/22.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/gsagnol/picos/issues/22#event-648037059

## 

Atenciosamente,

José Roberto.
