### ISSUE TITLE
Sum of QuadExp

### ISSUE THREAD

**Issue by zaccharieramzi** [gsagnol/picos#29]
Hi,

Thank you for your project.
I am currently working with picos to solve an SDP-relaxation problem with triangular inequalities (https://arxiv.org/pdf/1305.1681.pdf). Therefore, I want, for the objective function, to be able to sum `QuadExp`. But it's not possible I think due to the way `sum` is coded. Indeed, [here](https://github.com/gsagnol/picos/blob/master_github/picos/tools.py#L154) we take `factors` from `exp`, but from what I read in the [docs](http://picos.zib.de/expression.html#quadexp), `QuadExp` doesn't have any. As a consequence, I get this error :
```
AttributeError: 'QuadExp' object has no attribute 'factors'
```
Do you know how I should proceed ?

**Comment by gsagnol** [comment]
Hi,

sorry for the late answer.
I'm not sure to understand your problem:

I can sum quadratic expressions, e.g.

import picos as pic
import cvxopt as cvx

P = pic.Problem()
x = P.add_variable('x',2)
Q = cvx.normal(2,2);Q = Q+Q.T
R = cvx.normal(2,2); R = R+R.T
print x.T*Q*x + x.T*R*x

Maybe there is a bug when you put a sum of quadratic expressions in the 
objective function of the problem?
In that case, try to convert your problem using the epigraph form, that 
is, if q1 and q2 are quadratic functions,

min q_1(x) + q_2(x)

becomes, by introducing 2 variables t_1 and t_2,

min t_1 + t_2
s.t. q_1(x) <=t_1
       q_2(x) <=t_2

Hope this solves your problem. Otherwise, send me a small example.

Best,
Guillaume.



Am 25.12.2016 um 10:52 schrieb zaccharieramzi:

**Comment by zaccharieramzi** [comment]
Hi,

Thank you for your answer. 
However, my problem was actually using the sum function of picos itself. Indeed I don't have a fixed number of quadratic expressions to sum therefore I would like to use the picos sum function.

Best,
Zaccharie

**Comment by gsagnol** [comment]
Allright, I get it.
I just uploaded a correction. The latest development version (on github) now allows one to do:
`pic.sum([x.T*Q*x, x.T*R*x])`

Best !

**Comment by duyvuleo** [comment]
I've checked out the latest version, but this feature (sum of QuadExp) did not work. Please advise! Thanks!

**Comment by gsagnol** [comment]
Sorry I overlooked your comment.

Can you tell me the output of 
``pic.sum([x.T*Q*x, x.T*R*x])``,
and which version of picos you are using? I cannot reproduce an error with the latest development version.
