### ISSUE TITLE
Poblems with Frobenius normal

### ISSUE THREAD

**Issue by dberma15** [gsagnol/picos#3]
Hi,

I'm trying to create an objective function based on the Frobenius normal. However, I keep getting an error. Here is my code:
from qutip import *
from cvxpy import *
import numpy as np
import picos as pic
import cvxopt as cvx

rho_estimate=fock_dm(2,0)
rho_estimate=cvx.matrix(rho_estimate[:,:])[:,:]
o=rho_estimate.size[0]
P=pic.Problem()
Z = P.add_variable('Z',(o,o),'hermitian')
P.set_objective('min',abs(rho_estimate-Z))
P.add_constraint(pic.tools.trace(Z)==1)
P.add_constraint(Z>>0)
P.solve()
print Z

However, I keep getting the following error:
"TypeError: <class 'picos.expression.AffinExp'> is not a valid type for a Constant value."

What am I doing wrong?

**Comment by gsagnol** [comment]
PICOS only supports linear (and quadratic) objective functions. So I think that the line that cause
the problem is "P.set_objective('min',abs(rho_estimate-Z))".

However, there is an easy workaround: You can introduce an auxiliary variable 't' and minimize it:
t = P.add_variable('t')
P.add_constraint(abs(rho_estimate-Z) <= t)
P.set_objective('min',t)                 

Does that help ?

**Comment by dberma15** [comment]
Thanks so much! I think it's working. I'll have to test it out a bit though and get back.

**Comment by gsagnol** [comment]
Hi,

The abs() function in picos represents the Frobenius norm.
I solved your problem by hand, and the solution you are displaying is 
correct:

Let Z = [x,z ; z,y]

Your problem rewrites:
min (x-1)^2 + (y-1)^2 + (z-0.005)^2 + (z-0.01)^2
s.t. x+y=1
       x>=0,y=0, xy >=z^2 (semidefinite constraint)

Clearly, at the optimum we have x=y=0.5. Then, it is clear that the 
constraint xy >=z^2 will not be saturated at the optimum
because the optimal value of z should be between  0.001 and 0.05, so we 
can forget it.
Finally, the optimal value of z is found by solving the unconstrained 
problem
min (z-0.005)^2 + (z-0.01)^2 = 2z^2 -0.03z +constant,
so z\* = 0.03/(2*2) = 0.0075

Note that since your problem only has real numbers, you should rather use
Z = P.add_variable('Z',(o,o),'symmetric')

This way, PICOS will not transform the 2x2 complex matrix variable into 
a 4x4 real-valued matrix.

Cheers,
Guillaume.
