### ISSUE TITLE
Is this a picos or cvxopt problem?

### ISSUE THREAD

**Issue by ziofil** [gsagnol/picos#36]
This SDP computes the spectral norm (largest singular value, aka operator norm):

```python
import picos as pic

P = pic.Problem()
t = P.add_variable('t',1)
Z = pic.new_param('Z',np.array(range(4)).reshape(2,2))
I = pic.new_param('I',np.identity(2))
P.add_constraint(((t*I & Z) // (Z.H & t*I))>>0 )

P.set_objective('min',t)
```
instead, `P.solve()`  gives me `-3.7025...` which is the negative of the spectral norm. You can see that the constraint is not respected, as already at `t=1` we have a negative eigenvalue:

```python
import numpy as np
np.linalg.eigvals(((I & Z) // (Z.H & I)).value)
```
gives `array([ 4.7025, -2.7025,  1.5402,  0.4598])`

**Comment by gsagnol** [comment]
This is because picos somehow solves a version of the problem where the objective is multiplied by -1, and forgets to multiply back before writing the 'obj' argument of the solution dictionary. I will check why. However, you can check that `t.value` and `P.obj_value()` both return the correct value of `3.7025...`.

**Comment by gsagnol** [comment]
OK, this should work, now.
