### ISSUE TITLE
shape problem in mosek

### ISSUE THREAD

**Issue by gsagnol** [gsagnol/picos#42]
When SDPs are not solved with the special option
``handleBarVars=False``

a ValueError is raised:
``ValueError: could not broadcast input array from shape (3,1) into shape (3)``

**Comment by shaladi** [comment]
So from the documentation it sounds like using 'handleBarVars=False' could significantly lower the performance because of PICOS creating a bunch of unnecessary variables. I have a rather large SDP that I've been trying to run, and I have to use 'handleBarVars=False' to make PICOS work with Mosek. But the solver typically runs out of memory or just hangs. Do you think this could be mainly due to this problem? As in, it would run more efficiently if this bug was not around?

**Comment by martindvds** [comment]
Did this problem exist in older versions, too?

**Comment by mjstahlberg** [comment]
@shaladi, it would be helpful if you could test your resource-intensive application with my new MOSEK implementation found at https://github.com/Viech/picos/tree/refactor/solvers. It does not handle "bar vars" in any special way, and my hope is that this is not necessary due to my new implementation turning out to be more efficient by pure chance. (Or due to MOSEK by now detecting bar vars on its own, as it probably should if it is making such a difference.)

**Comment by mjstahlberg** [comment]
Checking with another example I found that the new MOSEK API will also not detect constraints of the form X ≽ 0 when PICOS passes them in LMI form, so I brought back what is essentially the same as `handleBarVars`; constraints of that form are passed as variable domains now. Still it would be helpful if you could verify that your example computes a solution now.

**Comment by shaladi** [comment]
I haven't ran my SDP in a while, I'll see if I can dig it back up and run
it.

**Comment by gsagnol** [comment]
This issue is now managed under GL: https://gitlab.com/picos-api/picos/issues/42
