### ISSUE TITLE
Function LogDet

### ISSUE THREAD

**Issue by IgnacioRubioScola** [gsagnol/picos#45]
Does exist a function in PICOS to do Logdet (natural logarithm of the determinant)? 
Thank you in advance.

**Comment by gsagnol** [comment]
No, because Logdet is not second-order cone or semidefinite representable.
It would be possible to represent it using both the semidefinite cone and the exponential cone, though,
but this is not (yet) implemented.

However, the nth root of the determinant is implemented in picos. Usually, 
if you want to maximize the logdet, you can maximize the nth root instead.
Similarly, if you want to maximize a weighted sum of logdets,
maximizing the weighted geometric mean of the nth roots of determinants will do the trick.

Do you have a practical example in mind which cannot be handled by detrootn ?

**Comment by IgnacioRubioScola** [comment]
Ohh I didn't know the function detrootn, it works perfectly!!  Thank you very much!
