### ISSUE TITLE
Changing the value of a parameter within an added constraint

### ISSUE THREAD

**Issue by lorenz-halt** [gsagnol/picos#66]
Hello,
I want to implement a bisection on one parameter in a semiconvex problem.
Every iteration I have to alter one parameter (a factor) in one of my constraints, which is afterwards considered constant for this iteration. 

Currently I am deleting the constraint and readding the varied constraint again.
I am wondering if there is a better possibility by e.g. setting a new value to a picos.Parameter.

Thanks for your help!

Here an oversimplified example:
```python
import picos as pic

prob = pic.Problem()

# Variables
X = prob.add_variable('X', (3, 3), vtype='symmetric')

# Bisection parameter
beta = pic.new_param('beta', 0) # sign='positive'

# Constraints
constraint = prob.add_constraint(beta*X << 3, ret=True)

# solve with beta==0
prob.solve(solver='cvxopt')
print X


# beta.set_value(1)

# workaround
constraint.delete()
beta = pic.new_param('beta', 1) # sign='positive'
constraint = prob.add_constraint(beta*X << 3, ret=True)
# end workaround

# solve with beta==1
prob.solve(solver='cvxopt')
print X
```

**Comment by mjstahlberg** [comment]
Hello @ipa-lth,

to my knowledge, the CVXOPT solver does not keep an internal state, so even if there was a way to edit a constraint the problem would still be handed to the solver as a whole and solved again from scratch every time. PICOS will also re-export the problem to CVXOPT's format on every call to `solve`, as the performance gain from maintaining and updating CVXOPT's problem representation within PICOS _should_ be negligible compared to the solution time (and to the potential for bugs that statefulness brings).

Otherwise, for solvers that do have an internal problem representation that can be updated for some performance gain, PICOS generally just supports adding and removing constraints. I don't actually know if any solver _does_ support and benefit from constraint edits, and for every other solver editing a constraint would boil down to removing and re-adding the constraint internally, so you would not notice a difference to what you do now.

I suggest to write a function for your constraint edit, and you can try to do it without using `new_param` as your parameter is just a scalar that you can also pass as a float, saving that function call.

**Comment by lorenz-halt** [comment]
@Viech Thank you very much. I actually already wrote a function as suggested.

A sidenote: cvxpy allows editing of parameters like that and e.g. SCS has a warmstart flag, that utilizes previous solutions as initial guesses. However, picos/cvxopt is performing much better on my problem. For currently unknown reasons cvxpy/cvxopt is failing on the same problem.
